theme: jekyll-theme-hacker
title: "Spring 2019: Advanced Topics in Numerical Analysis: High Performance Computing"
description: "Cross-listed as MATH-GA.2012-001 and CSCI-GA 2945.001"
# logo: ./files/logo.png
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
